module.exports = {
    "classic": [
        { "id": 1, "category": "Comida", "text": "Qual é a cobertura de pizza que todo mundo odeia?" },
        { "id": 2, "category": "Cotidiano", "text": "Cite algo que você faz logo ao acordar." },
        { "id": 3, "category": "Cinema", "text": "Qual o pior lugar para levar alguém num primeiro encontro?" },
        { "id": 4, "category": "Animais", "text": "Qual animal você gostaria de ter se fosse do tamanho de um gato?" },
        { "id": 5, "category": "Superpoderes", "text": "Qual o superpoder mais inútil de todos?" },
        { "id": 6, "category": "Trabalho", "text": "O que você falaria para o seu chefe se não pudesse ser demitido?" },
        { "id": 7, "category": "Escola", "text": "Qual a matéria mais chata da escola?" },
        { "id": 8, "category": "Medo", "text": "Do que todo mundo tem medo mas finge que não?" },
        { "id": 9, "category": "Brasil", "text": "O que é mais brasileiro que futebol e samba?" },
        { "id": 10, "category": "Casa", "text": "Qual o objeto mais bagunçado da sua casa?" },
        { "id": 11, "category": "Comida", "text": "Qual comida você fingia gostar quando era criança?" },
        { "id": 12, "category": "Animais", "text": "Qual o animal mais inútil do planeta?" },
        { "id": 13, "category": "Cotidiano", "text": "Qual a tarefa doméstica que todo mundo deixa para depois?" },
        { "id": 14, "category": "Brasil", "text": "Qual a gíria brasileira mais engraçada?" },
        { "id": 15, "category": "Trabalho", "text": "Qual profissão você nunca teria coragem de exercer?" }
    ],
    "polemic": [
        { "id": 101, "category": "Polêmica", "text": "Qual reality show você participaria apenas pelo dinheiro?" },
        { "id": 102, "category": "Polêmica", "text": "Se pudesse deletar uma rede social do mundo, qual seria?" },
        { "id": 103, "category": "Polêmica", "text": "Qual celebridade todo mundo ama, menos você?" },
        { "id": 104, "category": "Polêmica", "text": "Qual a pior modinha da internet nos últimos anos?" },
        { "id": 105, "category": "Polêmica", "text": "Android ou iPhone: quem é o vilão?" },
        { "id": 106, "category": "Polêmica", "text": "Qual programa de TV deveria ser cancelado imediatamente?" },
        { "id": 107, "category": "Polêmica", "text": "Qual comida 'gourmet' é pura enganação?" },
        { "id": 108, "category": "Polêmica", "text": "Qual profissão é supervalorizada pela sociedade?" },
        { "id": 109, "category": "Polêmica", "text": "Qual trend do TikTok foi longe demais?" },
        { "id": 110, "category": "Polêmica", "text": "Qual filme famoso é totalmente superestimado?" }
    ],
    "philosophy": [
        { "id": 201, "category": "Filosofia", "text": "Se dinheiro não existisse, o que você faria da vida?" },
        { "id": 202, "category": "Filosofia", "text": "Qual a maior invenção da humanidade?" },
        { "id": 203, "category": "Filosofia", "text": "Se você pudesse viver para sempre, você aceitaria?" },
        { "id": 204, "category": "Filosofia", "text": "O destino existe ou criamos nosso próprio caminho?" },
        { "id": 205, "category": "Filosofia", "text": "Qual a idade ideal para se viver?" },
        { "id": 206, "category": "Filosofia", "text": "O que é mais importante: ser amado ou ser respeitado?" },
        { "id": 207, "category": "Filosofia", "text": "Prefere saber a data da sua morte ou a causa dela?" },
        { "id": 208, "category": "Filosofia", "text": "Qual sentido você escolheria perder se tivesse que escolher um?" },
        { "id": 209, "category": "Filosofia", "text": "É melhor viver 50 anos feliz ou 100 anos mediano?" },
        { "id": 210, "category": "Filosofia", "text": "O arrependimento ensina ou apenas machuca?" }
    ],
    "technology": [
        { "id": 301, "category": "Tecnologia", "text": "Qual app você verifica logo ao acordar?" },
        { "id": 302, "category": "Tecnologia", "text": "Qual tecnologia do passado você sente falta?" },
        { "id": 303, "category": "Tecnologia", "text": "Qual função do celular ninguém usa mas todo mundo tem?" },
        { "id": 304, "category": "Tecnologia", "text": "Qual a senha mais comum que as pessoas usam?" },
        { "id": 305, "category": "Tecnologia", "text": "Qual atualização de app piorou tudo?" },
        { "id": 306, "category": "Tecnologia", "text": "Qual rede social você usa mas tem vergonha de admitir?" },
        { "id": 307, "category": "Tecnologia", "text": "Qual a maior mentira que a tecnologia vendeu para nós?" },
        { "id": 308, "category": "Tecnologia", "text": "Qual recurso de IA você acha mais assustador?" },
        { "id": 309, "category": "Tecnologia", "text": "O que você mais pesquisa no Google?" },
        { "id": 310, "category": "Tecnologia", "text": "Qual emoji mais representa você?" }
    ],
    "relationships": [
        { "id": 401, "category": "Relacionamentos", "text": "Qual a pior desculpa para terminar um relacionamento?" },
        { "id": 402, "category": "Relacionamentos", "text": "Qual a red flag mais ignorada nos relacionamentos?" },
        { "id": 403, "category": "Relacionamentos", "text": "O que mata qualquer romance no primeiro encontro?" },
        { "id": 404, "category": "Relacionamentos", "text": "Qual mentirinha todo mundo conta no começo do namoro?" },
        { "id": 405, "category": "Relacionamentos", "text": "Qual o presente mais sem graça para dar ao parceiro?" },
        { "id": 406, "category": "Relacionamentos", "text": "Qual a pergunta que você nunca deve fazer no primeiro encontro?" },
        { "id": 407, "category": "Relacionamentos", "text": "Qual o defeito mais difícil de tolerar em alguém?" },
        { "id": 408, "category": "Relacionamentos", "text": "O que mais irrita em quem mora junto?" },
        { "id": 409, "category": "Relacionamentos", "text": "Qual conselho de relacionamento nunca funciona?" },
        { "id": 410, "category": "Relacionamentos", "text": "Qual o sinal de que a pessoa não está interessada?" }
    ],
    "nostalgia": [
        { "id": 501, "category": "Nostalgia", "text": "Qual brinquedo dos anos 90/2000 você mais sente falta?" },
        { "id": 502, "category": "Nostalgia", "text": "Qual programa infantil marcou sua infância?" },
        { "id": 503, "category": "Nostalgia", "text": "Qual música você cantava errado quando era criança?" },
        { "id": 504, "category": "Nostalgia", "text": "Qual lanche da escola era o mais disputado?" },
        { "id": 505, "category": "Nostalgia", "text": "Qual era o site que todo mundo acessava nos anos 2000?" },
        { "id": 506, "category": "Nostalgia", "text": "Qual filme você assistia repetidamente na infância?" },
        { "id": 507, "category": "Nostalgia", "text": "Qual jogo de videogame definiu sua geração?" },
        { "id": 508, "category": "Nostalgia", "text": "Qual revista todo adolescente lia escondido?" },
        { "id": 509, "category": "Nostalgia", "text": "Qual moda dos anos 2000 era ridícula mas todo mundo usava?" },
        { "id": 510, "category": "Nostalgia", "text": "Qual canal de TV você passava o dia inteiro assistindo?" }
    ],
    "embarrassing": [
        { "id": 601, "category": "Vergonha", "text": "Qual a coisa mais constrangedora que pode acontecer em público?" },
        { "id": 602, "category": "Vergonha", "text": "Qual música você canta no chuveiro mas nunca admitiria?" },
        { "id": 603, "category": "Vergonha", "text": "O que você faz quando está sozinho mas negaria até a morte?" },
        { "id": 604, "category": "Vergonha", "text": "Qual tipo de vídeo você assiste no YouTube às 3 da manhã?" },
        { "id": 605, "category": "Vergonha", "text": "Qual comida você come direto da panela quando está sozinho?" },
        { "id": 606, "category": "Vergonha", "text": "Qual o lugar mais estranho onde você já chorou?" },
        { "id": 607, "category": "Vergonha", "text": "Qual série trash você maratonou inteira?" },
        { "id": 608, "category": "Vergonha", "text": "Qual a mentira mais boba que você já contou?" },
        { "id": 609, "category": "Vergonha", "text": "O que você comprou por impulso e se arrependeu?" },
        { "id": 610, "category": "Vergonha", "text": "Qual o apelido mais ridículo que você já teve?" }
    ],
    "travel": [
        { "id": 701, "category": "Viagem", "text": "Qual o lugar mais superestimado do Brasil?" },
        { "id": 702, "category": "Viagem", "text": "O que ninguém te conta sobre viajar de avião?" },
        { "id": 703, "category": "Viagem", "text": "Qual o país que todo mundo quer visitar?" },
        { "id": 704, "category": "Viagem", "text": "Qual a pior parte de qualquer viagem?" },
        { "id": 705, "category": "Viagem", "text": "O que você sempre esquece de colocar na mala?" },
        { "id": 706, "category": "Viagem", "text": "Qual cidade brasileira você visitaria de novo?" },
        { "id": 707, "category": "Viagem", "text": "Qual o tipo mais irritante de turista?" },
        { "id": 708, "category": "Viagem", "text": "O que todo brasileiro leva quando viaja?" },
        { "id": 709, "category": "Viagem", "text": "Qual o souvenir mais inútil que existe?" },
        { "id": 710, "category": "Viagem", "text": "Praia ou montanha: qual é o melhor destino?" }
    ],
    "money": [
        { "id": 801, "category": "Dinheiro", "text": "No que a maioria das pessoas gasta dinheiro à toa?" },
        { "id": 802, "category": "Dinheiro", "text": "Qual o primeiro item de luxo que você compraria se ficasse rico?" },
        { "id": 803, "category": "Dinheiro", "text": "Qual serviço de assinatura não vale o preço?" },
        { "id": 804, "category": "Dinheiro", "text": "O que custa mais caro do que deveria?" },
        { "id": 805, "category": "Dinheiro", "text": "Qual a desculpa mais comum para não guardar dinheiro?" },
        { "id": 806, "category": "Dinheiro", "text": "Em qual Black Friday todo mundo cai no golpe?" },
        { "id": 807, "category": "Dinheiro", "text": "Qual investimento todo mundo fala que é bom?" },
        { "id": 808, "category": "Dinheiro", "text": "O que é mais difícil: ganhar ou economizar dinheiro?" },
        { "id": 809, "category": "Dinheiro", "text": "Qual a compra que mais gera arrependimento?" },
        { "id": 810, "category": "Dinheiro", "text": "Quanto dinheiro seria suficiente para você nunca mais trabalhar?" }
    ],
    "party": [
        { "id": 901, "category": "Festa", "text": "Qual o pior tipo de pessoa numa festa?" },
        { "id": 902, "category": "Festa", "text": "Qual música nunca pode faltar num churrasco?" },
        { "id": 903, "category": "Festa", "text": "Qual a desculpa mais usada para sair cedo de uma festa?" },
        { "id": 904, "category": "Festa", "text": "Qual bebida todo mundo toma mas ninguém gosta?" },
        { "id": 905, "category": "Festa", "text": "O que sempre falta em toda festa?" },
        { "id": 906, "category": "Festa", "text": "Qual o petisco essencial de qualquer festa brasileira?" },
        { "id": 907, "category": "Festa", "text": "Qual o horário que uma festa fica realmente boa?" },
        { "id": 908, "category": "Festa", "text": "Qual a pior música para tocar numa festa?" },
        { "id": 909, "category": "Festa", "text": "O que ninguém leva mas todo mundo usa na festa?" },
        { "id": 910, "category": "Festa", "text": "Qual a desculpa mais usada para não ir numa festa?" }
    ]
    "cinema": [
        { "id": 1001, "category": "Cinema", "text": "Qual o filme que todo mundo chora no final?" },
        { "id": 1002, "category": "Cinema", "text": "Qual o pior clichê dos filmes de terror?" },
        { "id": 1003, "category": "Cinema", "text": "Qual ator/atriz está em todos os filmes?" },
        { "id": 1004, "category": "Cinema", "text": "Qual filme você assistiu mais de 5 vezes?" },
        { "id": 1005, "category": "Cinema", "text": "Qual o snack obrigatório no cinema?" },
        { "id": 1006, "category": "Cinema", "text": "Qual franquia de filme deveria ter parado no primeiro?" },
        { "id": 1007, "category": "Cinema", "text": "Qual o filme mais chato que todo mundo finge que gostou?" },
        { "id": 1008, "category": "Cinema", "text": "Qual dublador brasileiro todo mundo reconhece a voz?" },
        { "id": 1009, "category": "Cinema", "text": "Qual filme de comédia romântica é o mais clichê?" },
        { "id": 1010, "category": "Cinema", "text": "Qual vilão de filme é o mais icônico?" },
        { "id": 1011, "category": "Cinema", "text": "Qual o filme que você nunca assistiu mas finge que já?" },
        { "id": 1012, "category": "Cinema", "text": "Qual gênero de filme você sempre foge?" },
        { "id": 1013, "category": "Cinema", "text": "Qual filme brasileiro todo mundo deveria assistir?" },
        { "id": 1014, "category": "Cinema", "text": "Qual a cena mais icônica do cinema?" },
        { "id": 1015, "category": "Cinema", "text": "Qual filme de Natal passa todo ano na TV?" }
    ],
    "comics": [
        { "id": 1101, "category": "Quadrinhos", "text": "Qual o super-herói mais superestimado?" },
        { "id": 1102, "category": "Quadrinhos", "text": "Marvel ou DC: qual é melhor?" },
        { "id": 1103, "category": "Quadrinhos", "text": "Qual o superpoder que todo mundo gostaria de ter?" },
        { "id": 1104, "category": "Quadrinhos", "text": "Qual vilão é mais legal que o herói?" },
        { "id": 1105, "category": "Quadrinhos", "text": "Qual o pior filme de super-herói já feito?" },
        { "id": 1106, "category": "Quadrinhos", "text": "Qual mangá/anime todo mundo já assistiu?" },
        { "id": 1107, "category": "Quadrinhos", "text": "Qual personagem da Turma da Mônica você mais se identifica?" },
        { "id": 1108, "category": "Quadrinhos", "text": "Qual HQ brasileira marcou sua infância?" },
        { "id": 1109, "category": "Quadrinhos", "text": "Qual super-herói deveria ter um filme solo?" },
        { "id": 1110, "category": "Quadrinhos", "text": "Qual o Batman mais icônico do cinema?" },
        { "id": 1111, "category": "Quadrinhos", "text": "Qual personagem de anime é o mais forte?" },
        { "id": 1112, "category": "Quadrinhos", "text": "Qual crossover de quadrinhos você gostaria de ver?" },
        { "id": 1113, "category": "Quadrinhos", "text": "Qual vilão da DC é o mais cruel?" },
        { "id": 1114, "category": "Quadrinhos", "text": "Qual super-herói tem o uniforme mais ridículo?" },
        { "id": 1115, "category": "Quadrinhos", "text": "Qual universo é mais sombrio: Marvel ou DC?" }
    ],
    "popculture": [
        { "id": 1201, "category": "Cultura Pop", "text": "Qual meme nunca sai de moda?" },
        { "id": 1202, "category": "Cultura Pop", "text": "Qual série todo mundo assistiu durante a pandemia?" },
        { "id": 1203, "category": "Cultura Pop", "text": "Qual música grudenta você não consegue tirar da cabeça?" },
        { "id": 1204, "category": "Cultura Pop", "text": "Qual casal de celebridades você torce para voltar?" },
        { "id": 1205, "category": "Cultura Pop", "text": "Qual trend do TikTok todo mundo fez?" },
        { "id": 1206, "category": "Cultura Pop", "text": "Qual reality show brasileiro é o mais viciante?" },
        { "id": 1207, "category": "Cultura Pop", "text": "Qual banda/cantor marcou os anos 2000?" },
        { "id": 1208, "category": "Cultura Pop", "text": "Qual série da Netflix você maratonou em um dia?" },
        { "id": 1209, "category": "Cultura Pop", "text": "Qual influencer digital todo mundo conhece?" },
        { "id": 1210, "category": "Cultura Pop", "text": "Qual polêmica de famoso foi mais absurda?" },
        { "id": 1211, "category": "Cultura Pop", "text": "Qual música toca em todo aniversário?" },
        { "id": 1212, "category": "Cultura Pop", "text": "Qual youtuber brasileiro fez mais sucesso?" },
        { "id": 1213, "category": "Cultura Pop", "text": "Qual personagem de série virou meme?" },
        { "id": 1214, "category": "Cultura Pop", "text": "Qual música brasileira virou hit internacional?" },
        { "id": 1215, "category": "Cultura Pop", "text": "Qual podcast todo mundo está ouvindo?" },
        { "id": 1216, "category": "Cultura Pop", "text": "Qual drag queen brasileira é mais famosa?" },
        { "id": 1217, "category": "Cultura Pop", "text": "Qual o meme brasileiro mais exportado?" },
        { "id": 1218, "category": "Cultura Pop", "text": "Qual série coreana todo mundo viciou?" },
        { "id": 1219, "category": "Cultura Pop", "text": "Qual funkeiro/a está dominando atualmente?" },
        { "id": 1220, "category": "Cultura Pop", "text": "Qual programa de auditório marcou a TV brasileira?" }
    ]
};